#include <fstream>
#include <iostream>

#include "minet/common/Assert.h"
#include "minet/components/BasicDispatcher.h"
#include "minet/components/BasicServer.h"
#include "minet/components/LoggerFactory.h"
#include "minet/core/WebHost.h"
#include "minet/core/WebHostBuilder.h"

MINET_BEGIN

static void _PrintBanner();

WebHostBuilder::WebHostBuilder(std::string appsettingsPath)
    : _appSettingsPath(std::move(appsettingsPath)), _container(mioc::ServiceContainer::New(true))
{
    _PrintBanner();
    _LoadSettings();
}

WebHostBuilder& WebHostBuilder::Register(const std::string& path, const Ref<IRequestHandler>& handler)
{
    _handlers[path] = handler;
    return *this;
}

Ref<WebHost> WebHostBuilder::Build()
{
    // Get logger.
    Ref<ILoggerFactory> loggerFactory = _container->Resolve<ILoggerFactory>();
    MINET_ASSERT(loggerFactory);

    // Create request dispatcher.
    Ref<IRequestDispatcher> dispatcher = _container->Resolve<IRequestDispatcher>();
    MINET_ASSERT(dispatcher);
    dispatcher->SetLogger(loggerFactory->GetLogger("RequestDispatcher"));
    for (const auto& [path, handler] : _handlers)
    {
        dispatcher->Register(path, handler);
    }

    // Get server.
    Ref<IServer> server = _container->Resolve<IServer>();
    MINET_ASSERT(server);
    server->SetLogger(loggerFactory->GetLogger("Server"));

    // Build Web host.
    Ref<WebHost> host = CreateRef<WebHost>(new WebHost(server, dispatcher, _container));
    host->SetLogger(loggerFactory->GetLogger("WebHost"));

    return host;
}

/**
 * See demo/appsettings.json for more information.
 */
void WebHostBuilder::_LoadSettings()
{
    using namespace nlohmann;

    if (_appSettingsPath.empty())
    {
        _config = json::object();
    }
    else
    {
        std::cout << "Loading app settings from " << _appSettingsPath << std::endl;
        std::ifstream file(_appSettingsPath);
        if (file.is_open())
        {
            _config = json::parse(file, nullptr, false, true);
        }
        else
        {
            _config = json::object();
            std::cerr << "No " << _appSettingsPath << " found, use default settings." << std::endl;
        }
        file.close();
    }

    if (_config.is_discarded())
    {
        std::cerr << "Failed to parse app settings file: " << _appSettingsPath << std::endl;
        abort();
    }

    _LoadServerSettings(_config.value("server", nlohmann::json::object()));
    _LoadLoggingSettings(_config.value("logging", nlohmann::json::object()));
}

void WebHostBuilder::_LoadServerSettings(const nlohmann::json& config)
{
    int port = config.value("port", 5000);
    if (port <= 0 || port > 65535)
    {
        std::cerr << "Invalid port number: " << port << ", use default 5000 instead." << std::endl;
        port = 5000;
    }
    _container->AddSingleton<ServerConfig>(CreateRef<ServerConfig>(new ServerConfig{ static_cast<uint16_t>(port) }));

    std::string name = config.value("name", "Basic");
    if (name == BasicServer::Identifier())
    {
        _container->AddSingleton<IServer, BasicServer, ServerConfig>();
        _container->AddSingleton<IRequestDispatcher, BasicDispatcher>();
    }
    else
    {
        std::cerr << "Invalid server name: " << name << std::endl;
        abort();
    }
}

void WebHostBuilder::_LoadLoggingSettings(const nlohmann::json& config)
{
    Ref<LoggerConfig> loggerConfig = CreateRef<LoggerConfig>();
    bool hasRoot = false;

    for (auto it = config.begin(); it != config.end(); ++it)
    {
        std::string name = it.key();
        nlohmann::json spec = it.value();
        LogLevel level = ParseLogLevel(spec.value("level", "Debug"));
        if (level == LogLevel::Invalid)
        {
            std::cerr << "Invalid log level: " << spec.value("level", "Debug") << ", use default Debug instead."
                      << std::endl;
            level = LogLevel::Debug;
        }
        std::vector<std::string> sinks = spec.value("sinks", std::vector<std::string>{ "stdout" });

        if (name == "root")
        {
            loggerConfig->DefaultLevel = level;
            loggerConfig->DefaultSinks = sinks;
            hasRoot = true;
        }
        else
        {
            loggerConfig->Specifications[name] = { name, level, sinks };
        }
    }

    /**
     * In case there is no root logger, we will set the default settings.
     */
    if (!hasRoot)
    {
        loggerConfig->DefaultLevel = LogLevel::Debug;
        loggerConfig->DefaultSinks = { "stdout" };
    }

    _container->AddSingleton<LoggerConfig>(loggerConfig);
    _container->AddSingleton<ILoggerFactory, LoggerFactory, LoggerConfig>();
}

/**
 * Banner generated by Text to ASCII Art Generator (TAAG).
 * @see https://patorjk.com/software/taag/#p=display&f=Slant&t=minet%20core
 */
void _PrintBanner()
{
    static bool printed = false;
    if (printed)
    {
        return;
    }

    static const char* banner = R"(
              _            __                         
   ____ ___  (_)___  ___  / /_    _________  ________ 
  / __ `__ \/ / __ \/ _ \/ __/   / ___/ __ \/ ___/ _ \
 / / / / / / / / / /  __/ /_    / /__/ /_/ / /  /  __/
/_/ /_/ /_/_/_/ /_/\___/\__/    \___/\____/_/   \___/
------------------------------------------------------
  A C++ HTTP server framework mimicking ASP.NET Core
)";
    std::cout << banner << std::endl;
}

MINET_END
